version: 2

updates:
  - package-ecosystem: "conda"
    directories:
      - "/nextflow/modules/**/*"
    schedule:
      interval: "weekly"

    groups:
      same-dependency-across-modules:
        patterns:
          - "*"
        group-by: "dependency-name"