# environment.yml

channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::samtools=1.24
  - bioconda::minibwa=0.7
  - bioconda::seqkit=2.13.0
  - bioconda::dupblaster=0.3.0
  - bioconda::seqtk=1.5
  - bioconda::fastp=1.3.6
  - conda-forge::curl=8.21.0
  - conda-forge::python=3.14.6
  - conda-forge::pip
  - pip:
    - hydrastream==1.2.0